#!/bin/sh

SCRIPT_DIR=$( readlink -f $( dirname -- "$0" ) )
. $SCRIPT_DIR/backup-online-s3

if [ "$CRON" = "1" ]; then
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 30 seconds..."'
sleep 10
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 20 seconds..."'
sleep 10
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 10 seconds..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 9 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 8 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 7 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 6 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 5 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 4 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 3 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 2 seconds ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "LIVE CLOUD backup in 1 second ..."'
sleep 1
echo "n" | ~/pzserver sd 'servermsg "ONLINE CLOUD BACKUP STARTED"'
fi

sync
echo "n" | ~/pzserver sd 'save'
sync
~/bin/restic backup ~/Zomboid --exclude ~/Zomboid/Logs --exclude ~/log --exclude ~/Zomboid/backups/startup

if [ "$CRON" = "1" ]; then
echo "n" | ~/pzserver sd 'servermsg "ONLINE CLOUD BACKUP COMPLETED"'
fi
